### ISSUE TITLE
Windows Machine Learning ImageFeatureValue and TensorFloat object cannot convert to winrt::object::Object

### ISSUE THREAD

**Issue by ryanlai2** [microsoft/winrt-rs#315]
The [LearningModelBinding Bind Method](https://docs.microsoft.com/en-us/uwp/api/windows.ai.machinelearning.learningmodelbinding.bind?view=winrt-19041) Bind(String, Object) cannot bind ImageFeatureValue and TensorFloat even though they both inherit from Object.

```
let input_image_feature_value = ImageFeatureValue::create_from_video_frame(input_image_videoframe)?;
let bind_result = binding.bind("data_0", input_image_feature_value);
```
error: 
`std::convert::From<microsoft::ai::machine_learning::ImageFeatureValue>` is not implemented for `winrt::param::Param<'_, winrt::object::Object>

**Comment by rylev** [comment]
Hey Ryan. This has been fixed by #297. Unfortunately this is not yet on crates.io since we're waiting for the release of Rust 1.46 to drop (on the 27th of August). Until then you'll have to reference WinRT-rs through git. 
```
[dependencies]
winrt_macros = { git = "https://github.com/microsoft/winrt-rs",  version = "0.7.2" }
```

**Comment by ryanlai2** [comment]
Hey Ryan, thanks for the explanation. I am still having issues, can you give me more guidance?

Here are the dependencies of my toml : 
```
[dependencies]
winrt = "0.7.2"
winrt_macros = { git = "https://github.com/microsoft/winrt-rs",  version = "0.7.2" }

[build-dependencies]
winrt = "0.7.2"

[package.metadata.winrt.dependencies]
"Microsoft.AI.MachineLearning" = "1.3.0"
```
Now that I depend on the github version for winrt_macros, to install  cargo winrt do I run this command:
``` cargo install cargo-winrt -f``` 
or this command 
```  cargo install --git https://github.com/microsoft/winrt-rs cargo-winrt ```

If I run ```  cargo install --git https://github.com/microsoft/winrt-rs cargo-winrt ```, when I build I run into this error ```error[E0658]: `while` is not allowed in a `const fn```

**Comment by rylev** [comment]
Since the new version of WinRT-rs requires Rust 1.46 which is not out yet, you need to use the beta version of the compiler:
```
rustup install beta
rustup override set beta
```

Then try again. Let me know if this helps!

**Comment by ryanlai2** [comment]
It works, thank you Ryan! One last question: Is there a way to change from IInspectable to Tensorfloat in Rust?

Normally in C++ it's like this:
```
auto lookupResult = results.Outputs().Lookup(L"softmaxout_1"); // this is an IInspectable
auto resultTensor = lookupResult.as<TensorFloat>(); // how to use ".as<>" in Rust?
```

Thanks!

**Comment by kennykerr** [comment]
The `ComInterface` trait provides the `query` and `try_query` methods for this ([although they are poorly named and will likely be renamed shortly](https://github.com/microsoft/winrt-rs/issues/302)).
